### ISSUE TITLE
Unify and improve database connection configs

### ISSUE THREAD

**Issue by rauanmayemir** [spiral/database#40] opened 2020-02-23 09:30 UTC
Currently, there are too many indirections in the way spiral database configs can be written.

E.g here's what's being used for spiral's test configs:

```
'postgres'  => [
    'driver'     => Database\Driver\Postgres\PostgresDriver::class,
    'check'      => static function () {
        return !in_array('pgsql', \PDO::getAvailableDrivers(), true);
    },
    'conn'       => 'pgsql:host=127.0.0.1;port=15432;dbname=spiral',
    'user'       => 'postgres',
    'pass'       => 'postgres',
    'queryCache' => 100
],
```

And here's a latest(?) config example:

```
'postgres' => [
    'driver' => Spiral\Database\Driver\Postgres\PostgresDriver::class,
    'options' => [
        'connection' => 'pgsql:host=localhost;dbname=spiral',
        'username' => 'username',
        'password' => 'password',
        'options' => [
            PDO::ATTR_EMULATE_PREPARES => true,
            PDO::ATTR_STRINGIFY_FETCHES => true,
        ],
    ],
],
```

We could keep backward compatibility, but improve configs and update all the examples, docs, tests. I would like to suggest the following improvements:

1. Drop the first nested `options` key and write connection properties in the root config
2. Use `dsn` instead of  `connection`/`conn`
3. Add `host`, `port`, and `dbname` configs. (but ignore them if `dsn` is set explicitly - I believe that's how it's done everywhere else)
4. Use `dotenv` in examples to allow for easier adoption

Following these suggestions, a config would look like:

```
'postgres' => [
    'driver' => Spiral\Database\Driver\Postgres\PostgresDriver::class,
    'host' => env('DB_HOST'),
    'port' => env('DB_PORT'),
    'dbname' => env('DB_DATABASE'),
    'username' => env('DB_USERNAME'),
    'password' => env('DB_PASSWORD'),
    'options' => [
        PDO::ATTR_EMULATE_PREPARES => true,
        PDO::ATTR_STRINGIFY_FETCHES => true,
    ],
],
```

Not so coincidentally, this looks almost exactly like Laravel config.
I could take a crack at this once we agree on the format.

**Comment by xorock** [comment] 2020-03-28 15:13
Thank you for the advice. Examples in the documentation do not work. There is no word about the fact that the entire connection (username, password, connection) block must also be wrapped in options. As a result, I received the 'invalid data source name' error.

**Comment by wolfy-j** [comment] 2020-03-28 15:27
@xorock It does not need to be wrapped in options. Can you provide me an example which does not work for you? We will improve the documentation! 

@rauanmayemir if we can backward compatibility to classic DSN declaration I'm all for it in 2.*.

**Comment by wolfy-j** [comment] 2020-03-28 15:28
The `options` were actually an older format. Where did you found it?

**Comment by xorock** [comment] 2020-03-28 16:55
I'm new to Spiral so first I created a new project `composer create-project spiral/app` - all packages should be in latest version.

database.php that works:

```php
<?php

declare(strict_types = 1);

use Spiral\Database\Driver\Postgres\PostgresDriver;

return [
    'default' => 'primary',
    'databases' => [
        'primary' => [
            'driver' => 'postgres',
        ],
    ],
    'drivers' => [
        'postgres' => [
            'driver' => PostgresDriver::class,
            'options' => [
                'connection' => 'pgsql:host=localhost;port=5432;dbname=' . env('DB_NAME'),
                'username' => env('DB_USERNAME'),
                'password' => env('DB_PASSWORD'),
                'options' => [],
                'profiling' => true,
            ],
        ],
    ],
];
```

Inside HomeController@index:
`dump($this->db->getDriver());`

```
Spiral\Database\Driver\Postgres\PostgresDriver object 
(
·    addr = string(42) pgsql:host=localhost;port=5432;dbname=test
·    source = string(4) test
·    connected = boolean(1) true
·    options = array(3)
·    [
·    ·    [8] = integer(1) 0
·    ·    [3] = integer(1) 2
·    ·    [20] = boolean(0) false
·    ]
)
```

According to docs this should work:

```
return [
    'default' => 'primary',
    'databases' => [
        'primary' => [
            'driver' => 'postgres',
        ],
    ],
    'drivers' => [
        'postgres' => [
            'driver' => PostgresDriver::class,
            'connection' => 'pgsql:host=localhost;port=5432;dbname=' . env('DB_NAME'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'options' => [],
            'profiling' => true,
        ],
    ],
];
```

but:

```
Spiral\Database\Driver\Postgres\PostgresDriver object 
(
·    addr = string(0) 
·    source = string(1) *
·    connected = boolean(0) false
·    options = array(3)
·    [
·    ·    [8] = integer(1) 0
·    ·    [3] = integer(1) 2
·    ·    [20] = boolean(0) false
·    ]
)
```

DSN/user/pass is empty. `dump($this->db->select('*')->from('sample_table')->fetchAll());`:

`Spiral\Database\Exception\StatementException: invalid data source name in D:\Server\spiral\vendor\spiral\database\src\Driver\Postgres\PostgresDriver.php at line 141
• caused by PDOException: invalid data source name in D:\Server\spiral\vendor\spiral\database\src\Driver\Driver.php at line 664`


```
php app.php db:list
+------------+-----------+----------+---------+--------------------------+---------+----------------+
| Name (ID): | Database: | Driver:  | Prefix: | Status:                  | Tables: | Count Records: |
+------------+-----------+----------+---------+--------------------------+---------+----------------+
| primary    | *         | Postgres | ---     | invalid data source name | ---     | ---            |
+------------+-----------+----------+---------+--------------------------+---------+----------------+
```

With extra options key:

```
php app.php db:list
+------------+-----------+----------+---------+-----------+--------------+----------------+
| Name (ID): | Database: | Driver:  | Prefix: | Status:   | Tables:      | Count Records: |
+------------+-----------+----------+---------+-----------+--------------+----------------+
| primary    | test      | Postgres | ---     | connected | sample_table | 1              |
|            |           |          |         |           | migrations   | 1              |
+------------+-----------+----------+---------+-----------+--------------+----------------+
```

I also tried `public function index(Database $primary): string` with no luck.

**Comment by krwu** [comment] 2020-04-05 14:05
Unwrapped parameters can not be combined with `options`.

The old unwrapped form works:

```php
'mysql' => [
    'driver'     => Driver\MySQL\MySQLDriver::class,
    'options' => [
        'connection' => sprintf('mysql:host=%s;dbname=%s', env('DB_HOST'), env('DB_NAME')),
        'username'   => env('DB_USER'),
        'password'   => env('DB_PASSWORD'),
    ]
]
```

The unwrapped form works, too:

```php
'mysql' => [
    'driver'     => Driver\MySQL\MySQLDriver::class,
    'connection' => sprintf('mysql:host=%s;dbname=%s', env('DB_HOST'), env('DB_NAME')),
    'username'   => env('DB_USER'),
    'password'   => env('DB_PASSWORD'),
]
```

But you can not add `options` to the second form, no matter the `options` array is empty or not:

```php
'mysql' => [
    'driver'     => Driver\MySQL\MySQLDriver::class,
    'connection' => sprintf('mysql:host=%s;dbname=%s', env('DB_HOST'), env('DB_NAME')),
    'username'   => env('DB_USER'),
    'password'   => env('DB_PASSWORD'),
    'options' => [], // this cause "invalid data source name"
]
```

```php
'mysql' => [
    'driver'     => Driver\MySQL\MySQLDriver::class,
    'connection' => sprintf('mysql:host=%s;dbname=%s', env('DB_HOST'), env('DB_NAME')),
    'username'   => env('DB_USER'),
    'password'   => env('DB_PASSWORD'),
    // this cause "invalid data source name"
    'options' => [
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]
]
```

**Comment by roxblnfk** [comment] 2021-11-15 15:50
I think it was resolved in https://github.com/cycle/database/pull/14

**Closed as completed by roxblnfk** 2021-11-15 15:50 UTC
Labels: enhancement, help wanted
